/* ============================================
   CONSTANTS — Dropdown options for registration
   and the Smart Matching Engine
   ============================================ */

// ── Education Levels ──────────────────────────────────────────────
export const EDUCATION_LEVELS = [
  { value: "jhs", label: "Junior High School (Grade 7–10)" },
  { value: "shs", label: "Senior High School (Grade 11–12)" },
  { value: "college", label: "College / University" },
  { value: "vocational", label: "Vocational / Technical (TESDA)" },
];

// ── Grade / Year Levels per education type ────────────────────────
export const GRADE_LEVELS = {
  jhs: ["Grade 7", "Grade 8", "Grade 9", "Grade 10"],
  shs: [
    "Grade 11 – 1st Semester",
    "Grade 11 – 2nd Semester",
    "Grade 12 – 1st Semester",
    "Grade 12 – 2nd Semester",
  ],
  college: ["1st Year", "2nd Year", "3rd Year", "4th Year", "5th Year+"],
  vocational: ["1st Year", "2nd Year"],
};

// ── SHS Strands ───────────────────────────────────────────────────
export const SHS_STRANDS = [
  "STEM – Science, Technology, Engineering and Mathematics",
  "ABM – Accountancy, Business and Management",
  "HUMSS – Humanities and Social Sciences",
  "TVL – Technical-Vocational-Livelihood",
  "GAS – General Academic Strand",
  "Arts and Design Track",
  "Sports Track",
];

// ── JHS Track (used as "course" equivalent for JHS) ───────────────
export const JHS_TRACKS = [
  "Regular Junior High School Program",
  "Special Program in the Arts (SPA)",
  "Special Program in Sports (SPS)",
  "Special Program in Foreign Language (SPFL)",
  "Science, Technology and Engineering Program (STEP)",
];

// ── College Courses ───────────────────────────────────────────────
export const COURSES = [
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Computer Engineering",
  "Bachelor of Science in Electronics Engineering",
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Mechanical Engineering",
  "Bachelor of Science in Chemical Engineering",
  "Bachelor of Science in Industrial Engineering",
  "Bachelor of Science in Electrical Engineering",
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Medical Technology",
  "Bachelor of Science in Pharmacy",
  "Bachelor of Science in Physical Therapy",
  "Bachelor of Science in Radiologic Technology",
  "Bachelor of Science in Nutrition and Dietetics",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Economics",
  "Bachelor of Science in Marketing Management",
  "Bachelor of Science in Tourism Management",
  "Bachelor of Science in Hospitality Management",
  "Bachelor of Arts in Communication",
  "Bachelor of Arts in Political Science",
  "Bachelor of Arts in Sociology",
  "Bachelor of Arts in Psychology",
  "Bachelor of Science in Social Work",
  "Bachelor of Secondary Education",
  "Bachelor of Elementary Education",
  "Bachelor of Early Childhood Education",
  "Bachelor of Science in Architecture",
  "Bachelor of Science in Environmental Science",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Criminology",
  "Bachelor of Laws (LLB)",
  "Doctor of Medicine (MD)",
];

// ── Vocational / TESDA Courses ────────────────────────────────────
export const VOCATIONAL_COURSES = [
  "Automotive Servicing NC II",
  "Bread and Pastry Production NC II",
  "Caregiving NC II",
  "Computer Hardware Servicing NC II",
  "Consumer Electronics Servicing NC II",
  "Cookery NC II",
  "Driving NC II",
  "Electrical Installation and Maintenance NC II",
  "Electronics Products Assembly and Servicing NC II",
  "Fashion Design NC III",
  "Food and Beverage Services NC II",
  "Hairdressing NC II",
  "Housekeeping NC II",
  "HVAC Servicing NC II",
  "Massage Therapy NC II",
  "Plumbing NC II",
  "Programming NC IV",
  "Shielded Metal Arc Welding NC I",
  "Tile Setting NC II",
  "Tourism Promotion Services NC II",
];

// ── Cities & Barangays ───────────────────────────────────────────
export const CITIES = [
  "Quezon City",
  "Lucena City, Quezon",
  "Pagbilao, Quezon",
];

export const BARANGAYS_BY_CITY = {
  "Quezon City": [
    "Bagong Lipunan ng Crame",
    "Bagumbayan",
    "Bagumbuhay",
    "Bahay Toro",
    "Balong Bato",
    "Banlat",
    "Batasan Hills",
    "Culiat",
    "Commonwealth",
    "Don Manuel",
    "Escopa I",
    "Escopa II",
    "Escopa III",
    "Escopa IV",
    "Holy Spirit",
    "Immaculate Concepcion",
    "Kaligayahan",
    "Kamuning",
    "Katipunan",
    "Kristong Hari",
    "Krus na Ligas",
    "Laging Handa",
    "Malaya",
    "Mangga",
    "Manresa",
    "Mariana",
    "Masambong",
    "Matandang Balara",
    "New Era",
    "North Fairview",
    "Novaliches Proper",
    "Pasong Putik Proper",
    "Payatas",
    "Project 6",
    "Saint Ignatius",
    "Saint Peter",
    "Salvacion",
    "San Agustin",
    "San Antonio",
    "San Bartolome",
    "San Isidro Labrador I",
    "San Isidro Labrador II",
    "San Jose",
    "San Martin de Porres",
    "San Roque",
    "Sangandaan",
    "Santo Niño",
    "Sauyo",
    "Sikatuna Village",
    "Silangan",
    "Socorro",
    "Tagumpay",
    "Talayan",
    "Talipapa",
    "Tandang Sora",
    "Tatalon",
    "Teacher's Village East",
    "Teacher's Village West",
    "U.P. Campus",
    "Ugong Norte",
    "Veterans Village",
    "Villa Maria Clara",
    "West Triangle",
    "White Plains",
  ],
  "Lucena City, Quezon": [
    "Bagong Silang",
    "Bocohan",
    "Cotta",
    "Dalahican",
    "Domoit",
    "Gulang-Gulang",
    "Ibabang Dupay",
    "Ibabang Iyam",
    "Ibabang Talim",
    "Ilayang Dupay",
    "Ilayang Iyam",
    "Ilayang Talim",
    "Isabang",
    "Kanlurang Mayao",
    "Kapalangan",
    "Langgam",
    "Laurel",
    "Mapagsanggalang",
    "Mayao Kanluran",
    "Mayao Parada",
    "Mayao Silangan",
    "Mayao Timog",
    "Palayan",
    "Ransohan",
    "Salinas I",
    "Salinas II",
    "Salinas III",
    "Salinas IV",
    "Silangan Mayao",
    "Talao-Talao",
    "Tumayan",
  ],
  "Pagbilao, Quezon": [
    "Alupaye",
    "Bankaw",
    "Banuyo",
    "Bigo",
    "Binahaan",
    "Bukal",
    "Calantas",
    "Carepdepan",
    "Ibabang Polo",
    "Ilayang Polo",
    "Kanluran",
    "Kilo",
    "Lalo",
    "Lawigue",
    "Malinao",
    "Mambaling",
    "Masalukot I",
    "Masalukot II",
    "Masalukot III",
    "Masalukot IV",
    "Mataas na Parang",
    "Mayowe",
    "Pansol",
    "Poblacion",
    "Silangan",
    "Sta. Catalina Norte",
    "Sta. Catalina Sur",
    "Sto. Niño",
    "Tagbakin",
    "Tanum",
    "Tiaong",
  ],
};

// ── Monthly Household Income Brackets ────────────────────────────
export const INCOME_BRACKETS = [
  { value: "below-10k", label: "Below ₱10,000 / month" },
  { value: "10k-20k", label: "₱10,000 – ₱20,000 / month" },
  { value: "20k-40k", label: "₱20,000 – ₱40,000 / month" },
  { value: "40k-60k", label: "₱40,000 – ₱60,000 / month" },
  { value: "above-60k", label: "Above ₱60,000 / month" },
];

export const INCOME_RANK = {
  "below-10k": 1,
  "10k-20k": 2,
  "20k-40k": 3,
  "40k-60k": 4,
  "above-60k": 5,
};
