/* eslint-disable no-unused-vars */
import { INCOME_RANK } from "./constants";

// ============================================================
//  SCHOLARSHIPS — Full mock dataset with eligibility criteria
//
//  specialConditions[] — hard-gates that disqualify a user
//  immediately if they don't match. Possible values:
//    'pwd'           → must have PWD ID
//    'solo_parent'   → must be a solo parent or child of one
//    'female'        → must identify as female
//    'indigenous'    → must be from an indigenous community
// ============================================================
export const scholarships = [
  {
    id: 1,
    title: "Mayor's Educational Assistance Program",
    provider: "Local Government Unit",
    type: "LGU",
    amount: "₱10,000",
    amountRaw: 10000,
    deadline: "2026-08-15",
    slots: 50,
    slotsFilled: 45,
    description:
      "The Mayor's Educational Assistance Program (MEAP) is a flagship scholarship of the Local Government Unit designed to support academically deserving students from low-income families within the barangay. The program aims to reduce the dropout rate in tertiary education by providing direct financial assistance for tuition and school fees.",
    requirements: [
      "Certified true copy of latest grades (minimum GWA 85 / 1.75)",
      "Proof of enrolment / Registration Form",
      "Two (2) 2x2 ID photos",
      "Valid ID of parent or guardian",
    ],
    eligibility: {
      minGwa: 1.75,
      maxIncomeRank: 2,
      eligibleBarangays: [],
      eligibleCourses: [],
      specialConditions: [], // open to all
    },
  },
  {
    id: 2,
    title: "Barangay Academic Excellence Scholarship",
    provider: "Barangay Council",
    type: "Barangay",
    amount: "₱5,000",
    amountRaw: 5000,
    deadline: "2026-09-01",
    slots: 30,
    slotsFilled: 30,
    description:
      "Awarded by the Barangay Council to its most academically outstanding residents. This scholarship recognizes students who consistently maintain a high GWA and serve as inspirations to other youth in the community. Recipients receive a cash grant per semester plus a certificate of recognition.",
    requirements: [
      "Certified true copy of grades with GWA of at least 88 / 1.50",
      "Barangay Certificate of Residency (at least 2 years)",
      "Proof of enrollment",
      "One (1) 2x2 ID photo",
    ],
    eligibility: {
      minGwa: 1.5,
      maxIncomeRank: 3,
      eligibleBarangays: [
        "Bagong Lipunan ng Crame (QC)",
        "Bagumbayan (QC)",
        "Commonwealth (QC)",
        "Culiat (QC)",
        "Holy Spirit (QC)",
        "Kaligayahan (QC)",
        "Novaliches Proper (QC)",
        "Payatas (QC)",
        "Sauyo (QC)",
        "Tandang Sora (QC)",
      ],
      eligibleCourses: [],
      specialConditions: [],
    },
  },
  {
    id: 3,
    title: "SK STEM Excellence Grant",
    provider: "Sangguniang Kabataan",
    type: "SK",
    amount: "₱7,500",
    amountRaw: 7500,
    deadline: "2026-07-30",
    slots: 20,
    slotsFilled: 12,
    description:
      "The SK STEM Excellence Grant is designed to nurture the next generation of Filipino scientists, engineers, and technologists. Funded by the Sangguniang Kabataan, it exclusively supports students enrolled in Science, Technology, Engineering, and Mathematics (STEM) programs.",
    requirements: [
      "Proof of enrollment in a STEM-related course",
      "Latest grades with GWA of at least 87 / 1.60",
      'Essay: "How will your STEM education contribute to the community?" (500 words)',
      "Certificate of Residency in the Barangay",
    ],
    eligibility: {
      minGwa: 1.6,
      maxIncomeRank: 4,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Science in Computer Science",
        "Bachelor of Science in Information Technology",
        "Bachelor of Science in Computer Engineering",
        "Bachelor of Science in Electronics Engineering",
        "Bachelor of Science in Civil Engineering",
        "Bachelor of Science in Mechanical Engineering",
        "Bachelor of Science in Chemical Engineering",
        "Bachelor of Science in Industrial Engineering",
        "Bachelor of Science in Electrical Engineering",
        "Bachelor of Science in Environmental Science",
        "STEM – Science, Technology, Engineering and Mathematics",
      ],
      specialConditions: [],
    },
  },
  {
    id: 4,
    title: "CHED Tulong Dunong Scholarship",
    provider: "Commission on Higher Education (CHED)",
    type: "CHED",
    amount: "₱8,000",
    amountRaw: 8000,
    deadline: "2026-10-01",
    slots: 200,
    description:
      "The CHED Tulong Dunong Program (TDP) is a national scholarship program that provides financial assistance to poor but deserving students in public Higher Education Institutions (HEIs). The program covers tuition fees, miscellaneous expenses, and provides a living allowance to full-time scholars.",
    requirements: [
      "Accomplished CHED Tulong Dunong application form",
      "Form 137-A or Senior High School Report Card",
      "PSA Birth Certificate",
      "Barangay Certificate of Residency",
      "Proof of Enrollment",
    ],
    eligibility: {
      minGwa: 2.0,
      maxIncomeRank: 2,
      eligibleBarangays: [],
      eligibleCourses: [],
      specialConditions: [],
    },
  },
  {
    id: 5,
    title: "SM Foundation Scholarship Program",
    provider: "SM Foundation, Inc.",
    type: "Private/NGO",
    amount: "₱12,000",
    amountRaw: 12000,
    deadline: "2026-08-31",
    slots: 100,
    description:
      "The SM Foundation College Scholarship Program has been supporting the education of deserving students across the Philippines for over three decades. Scholars receive tuition and school fee coverage, a monthly stipend, and opportunities for internship placement within SM group of companies upon graduation.",
    requirements: [
      "Accomplished SM Foundation application form",
      "Latest certified true copy of grades (GWA 90 / 1.25 or better)",
      "PSA Birth Certificate",
      "Certificate of Enrollment / Admission",
      'Essay: "What does education mean to you?" (300–500 words)',
      "Recent 2x2 ID photo with white background",
    ],
    eligibility: {
      minGwa: 1.25,
      maxIncomeRank: 3,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Science in Business Administration",
        "Bachelor of Science in Accountancy",
        "Bachelor of Science in Computer Science",
        "Bachelor of Science in Information Technology",
        "Bachelor of Science in Marketing Management",
        "Bachelor of Science in Hospitality Management",
        "Bachelor of Science in Tourism Management",
        "Bachelor of Science in Economics",
      ],
      specialConditions: [],
    },
  },
  {
    id: 6,
    title: "DOST-SEI Undergraduate Scholarship",
    provider: "DOST – Science Education Institute",
    type: "Government",
    amount: "₱15,000",
    amountRaw: 15000,
    deadline: "2026-09-15",
    slots: 500,
    description:
      "The DOST-SEI Undergraduate Scholarship (Merit) is one of the most prestigious government scholarships in the Philippines, supporting students in priority science and engineering disciplines. Scholars receive a generous monthly stipend, book allowance, and tuition coverage at any DOST-accredited institution.",
    requirements: [
      "DOST-SEI Online application form (submitted via SEI portal)",
      "Senior High School Grade 12 Report Card or equivalent",
      "PSA Birth Certificate",
      "Certificate of Good Moral Character",
    ],
    eligibility: {
      minGwa: 1.4,
      maxIncomeRank: 4,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Science in Computer Science",
        "Bachelor of Science in Information Technology",
        "Bachelor of Science in Computer Engineering",
        "Bachelor of Science in Electronics Engineering",
        "Bachelor of Science in Civil Engineering",
        "Bachelor of Science in Mechanical Engineering",
        "Bachelor of Science in Chemical Engineering",
        "Bachelor of Science in Industrial Engineering",
        "Bachelor of Science in Electrical Engineering",
        "Bachelor of Science in Environmental Science",
        "Bachelor of Science in Agriculture",
      ],
      specialConditions: [],
    },
  },
  {
    id: 7,
    title: "Health Professions Scholarship (DOH)",
    provider: "Department of Health",
    type: "Government",
    amount: "₱18,000",
    amountRaw: 18000,
    deadline: "2026-11-30",
    slots: 150,
    description:
      "The DOH Health Professions Scholarship Program supports students in health-related fields to address the shortage of health professionals in underserved areas of the Philippines. In exchange, scholars commit to serve in public health facilities for a return service obligation after graduation.",
    requirements: [
      "DOH scholarship application form",
      "Certified true copy of grades (GWA 86 / 1.70)",
      "Medical Certificate",
      "PSA Birth Certificate",
      "Proof of enrollment in a health professions program",
      "Letter of intent stating commitment to return service",
    ],
    eligibility: {
      minGwa: 1.7,
      maxIncomeRank: 3,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Science in Nursing",
        "Bachelor of Science in Medical Technology",
        "Bachelor of Science in Pharmacy",
        "Bachelor of Science in Physical Therapy",
        "Bachelor of Science in Radiologic Technology",
        "Bachelor of Science in Nutrition and Dietetics",
        "Doctor of Medicine (MD)",
      ],
      specialConditions: [],
    },
  },
  {
    id: 8,
    title: "Future Educators Scholarship (DepEd)",
    provider: "Department of Education",
    type: "Government",
    amount: "₱6,000",
    amountRaw: 6000,
    deadline: "2026-09-30",
    slots: 80,
    description:
      "The Future Educators Scholarship is DepEd's response to the growing demand for quality teachers in public schools. The program provides financial aid to students in teacher education programs, with priority given to applicants who intend to serve in public school systems after graduation.",
    requirements: [
      "Accomplished DepEd application form",
      "Latest grades (GWA of at least 87 / 1.60)",
      "Certificate of Good Moral Character",
      "Barangay Certificate of Residency",
      'Essay: "Why do you want to become a teacher?" (400 words)',
      "Two (2) 2x2 ID photos",
    ],
    eligibility: {
      minGwa: 1.6,
      maxIncomeRank: 3,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Secondary Education",
        "Bachelor of Elementary Education",
        "Bachelor of Early Childhood Education",
      ],
      specialConditions: [],
    },
  },
  {
    id: 9,
    title: "Gawad sa Natatanging Iskolar (Barangay)",
    provider: "Barangay Tandang Sora",
    type: "Barangay",
    amount: "₱4,000",
    amountRaw: 4000,
    deadline: "2026-08-01",
    slots: 15,
    description:
      "Isang espesyal na grant mula sa Barangay Tandang Sora para sa mga natatanging mag-aaral na nakatira sa nasabing barangay. Layunin ng programa na gantimpalaan ang mga estudyanteng nagpapakita ng kahusayan sa pag-aaral at naglilingkod sa komunidad.",
    requirements: [
      "Patunay ng paninirahan sa Barangay Tandang Sora (hindi bababa sa 3 taon)",
      "Certified true copy ng pinakabagong marka (GWA 90 / 1.25)",
      "Sulat mula sa punong barangay",
      "Proof of enrollment",
      "Community service record (hindi bababa sa 40 oras)",
    ],
    eligibility: {
      minGwa: 1.25,
      maxIncomeRank: 5,
      eligibleBarangays: ["Tandang Sora (QC)"],
      eligibleCourses: [],
      specialConditions: [],
    },
  },
  {
    id: 10,
    title: "PWD/Solo Parent Educational Assistance",
    provider: "DSWD – Department of Social Welfare and Development",
    type: "Government",
    amount: "₱9,000",
    amountRaw: 9000,
    deadline: "2026-10-15",
    slots: 60,
    description:
      "The DSWD provides educational assistance to children of solo parents and persons with disabilities (PWD) enrolled in college. This program is committed to breaking the cycle of poverty by ensuring that marginalized sectors have access to tertiary education regardless of their circumstances.",
    requirements: [
      "DSWD application form",
      "Solo Parent ID (Republic Act 8972) OR PWD ID",
      "Certificate of Enrollment",
      "PSA Birth Certificate",
      "Certificate of Indigency or Income certificate",
      "Medical Certificate (for PWD applicants)",
    ],
    eligibility: {
      minGwa: 2.5,
      maxIncomeRank: 2,
      eligibleBarangays: [],
      eligibleCourses: [],
      // ← HARD GATE: user must be a PWD OR a solo parent / child of solo parent
      specialConditions: ["pwd_or_solo_parent"],
    },
  },
  {
    id: 11,
    title: "LGU IT Innovation Scholarship",
    provider: "Local Government Unit – ICT Office",
    type: "LGU",
    amount: "₱11,000",
    amountRaw: 11000,
    deadline: "2026-07-15",
    slots: 25,
    description:
      "The LGU IT Innovation Scholarship was established to prepare the barangay's youth for the digital economy. Scholars are not only given financial support but are also matched with mentors from local tech companies and invited to intern at the LGU's Digital Governance Center upon completion of their second year.",
    requirements: [
      "Accomplished LGU-ICT application form",
      "Grades showing consistent GWA of 1.50 or better",
      "Portfolio of any IT project, app, or code repository (GitHub link accepted)",
      'Motivation letter: "How will you use technology to serve your community?" (300–400 words)',
      "Barangay Certificate of Residency",
      "Proof of enrollment in an IT or CS program",
    ],
    eligibility: {
      minGwa: 1.5,
      maxIncomeRank: 4,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Science in Computer Science",
        "Bachelor of Science in Information Technology",
        "Bachelor of Science in Computer Engineering",
        "Bachelor of Science in Electronics Engineering",
      ],
      specialConditions: [],
    },
  },
  {
    id: 12,
    title: "Women in Leadership Scholarship",
    provider: "Philippine Commission on Women (PCW)",
    type: "Government",
    amount: "₱8,500",
    amountRaw: 8500,
    deadline: "2026-08-20",
    slots: 40,
    description:
      "The Women in Leadership Scholarship is a gender-responsive program by the Philippine Commission on Women. It supports female students who demonstrate exceptional leadership potential and academic merit, with a particular focus on courses related to governance, law, public policy, and social sciences.",
    requirements: [
      "PCW application form",
      "Certified true copy of grades (GWA 87 / 1.60)",
      "Proof of enrollment in eligible courses",
      "Leadership portfolio: list of positions held and community activities",
      "PSA Birth Certificate",
      "Barangay Clearance",
    ],
    eligibility: {
      minGwa: 1.6,
      maxIncomeRank: 4,
      eligibleBarangays: [],
      eligibleCourses: [
        "Bachelor of Arts in Political Science",
        "Bachelor of Arts in Sociology",
        "Bachelor of Arts in Psychology",
        "Bachelor of Laws (LLB)",
        "Bachelor of Science in Social Work",
        "Bachelor of Science in Economics",
        "Bachelor of Arts in Communication",
        "HUMSS – Humanities and Social Sciences",
      ],
      // ← HARD GATE: female applicants only
      specialConditions: ["female"],
    },
  },
  {
    id: 13,
    title: "Indigenous Peoples Education Scholarship (CHED-IP)",
    provider: "CHED – Indigenous Peoples Affairs",
    type: "Government",
    amount: "₱7,000",
    amountRaw: 7000,
    deadline: "2026-09-20",
    slots: 45,
    description:
      "The CHED-IP Education Scholarship is specifically designed for students who belong to an Indigenous Peoples (IP) community. It aims to preserve cultural heritage and promote equitable access to quality higher education for all ethnic communities in the Philippines.",
    requirements: [
      "CHED-IP application form",
      "Certificate of Tribal Membership or IP affiliation from NCIP",
      "Proof of enrollment",
      "PSA Birth Certificate",
      "Barangay Certification of residency",
      "Latest Report Card or Grades",
    ],
    eligibility: {
      minGwa: 2.0,
      maxIncomeRank: 3,
      eligibleBarangays: [],
      eligibleCourses: [],
      // ← HARD GATE: indigenous peoples only
      specialConditions: ["indigenous"],
    },
  },
];

// ============================================================
//  Admin mock applicant data for the Data Table
// ============================================================
export const applicants = [
  {
    id: 1,
    name: "Juan Dela Cruz",
    program: "Mayor's Educational Assistance Program",
    gpa: "1.50",
    matchScore: 98,
    appliedDate: "2026-05-20",
    status: "Under Review",
  },
  {
    id: 2,
    name: "Maria Clara",
    program: "Barangay Academic Excellence Scholarship",
    gpa: "1.25",
    matchScore: 95,
    appliedDate: "2026-05-18",
    status: "Approved",
  },
  {
    id: 3,
    name: "Jose Rizal",
    program: "Mayor's Educational Assistance Program",
    gpa: "1.75",
    matchScore: 82,
    appliedDate: "2026-05-22",
    status: "Pending",
  },
  {
    id: 4,
    name: "Andres Bonifacio",
    program: "DOST-SEI Undergraduate Scholarship",
    gpa: "1.30",
    matchScore: 99,
    appliedDate: "2026-05-19",
    status: "Approved",
  },
  {
    id: 5,
    name: "Gabriela Silang",
    program: "Women in Leadership Scholarship",
    gpa: "1.40",
    matchScore: 92,
    appliedDate: "2026-05-21",
    status: "Pending",
  },
  {
    id: 6,
    name: "Apolinario Mabini",
    program: "CHED Tulong Dunong Scholarship",
    gpa: "1.60",
    matchScore: 78,
    appliedDate: "2026-05-23",
    status: "Under Review",
  },
  {
    id: 7,
    name: "Melchora Aquino",
    program: "Health Professions Scholarship (DOH)",
    gpa: "1.45",
    matchScore: 88,
    appliedDate: "2026-05-17",
    status: "Approved",
  },
  {
    id: 8,
    name: "Emilio Aguinaldo",
    program: "SK STEM Excellence Grant",
    gpa: "1.55",
    matchScore: 85,
    appliedDate: "2026-05-20",
    status: "Pending",
  },
  {
    id: 9,
    name: "Gregorio del Pilar",
    program: "LGU IT Innovation Scholarship",
    gpa: "1.35",
    matchScore: 94,
    appliedDate: "2026-05-24",
    status: "Under Review",
  },
  {
    id: 10,
    name: "Tandang Basio Macunat",
    program: "PWD/Solo Parent Educational Assistance",
    gpa: "2.25",
    matchScore: 72,
    appliedDate: "2026-05-16",
    status: "Approved",
  },
];

// ============================================================
//  Admin Dashboard Metrics
// ============================================================
export const metrics = {
  activeScholarships: scholarships.length,
  pendingApplications: 45,
  approvedScholars: 128,
  totalApplicants: 312,
};
